### ISSUE TITLE
Bug with "bad playbill" button

### ISSUE THREAD

**Issue by lindsaymking** [YaleDHLab/ensemble-at-yale#66]
I noticed this morning that if you click "bad playbill" on the first Mark screen, and then click "done" to move on, the button persists as "done" rather than "next," meaning that you can never get to the other steps in the Mark workflow. The problem goes away with a page refresh, but would likely create a bunch of half-marked programs before someone realized that.

**Comment by duhaime** [comment]
Hmm, this is interesting. My understanding is that the bad playbill button is meant to designate that something about a playbill is fundamentally wrong and that the playbill should be fixed before it's marked/transcribed. With that understanding, if one clicks the bad playbill button, they wouldn't mark fields--they'd simply indicate they were done working on that playbill with the done button, then they'd confirm there's nothing left to do on the following screen. 

We could simplify that workflow by sending users to a new playbill if they mark their current playbill as bad, or we could use some other logic altogether. If someone marks a playbill as bad, what would the expected behavior be?

**Comment by lindsaymking** [comment]
The "bad playbill" button itself works fine, and you're right that users wouldn't mark anything. The problem is that the _next_ playbill the user gets to will still have the "done" button where it should have a "next" button. The "done" button should revert to "next" when the user sees the new (hopefully non-bad) playbill.

**Comment by duhaime** [comment]
Ahh, I see--this is odd! I'm going to have to dig in to uncover this bug...

**Comment by duhaime** [comment]
It looks like the Mark stage navigation logic was checking to see if `@state.badSubject` object was _defined_, but should have been checking to see if that variable equates to _true_. I fixed this on the deploy server: does the update behave as you'd expect? If so, I'll go ahead and close this ticket.

**Comment by lindsaymking** [comment]
It's reverting to "next" now. Thanks for figuring it out!

**Comment by duhaime** [comment]
Thanks for uncovering the bug!
